// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: account_information.proto

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccountInformationService_Get_FullMethodName = "/accountinformation.AccountInformationService/Get"
)

// AccountInformationServiceClient is the client API for AccountInformationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountInformationServiceClient interface {
	Get(ctx context.Context, in *ClientId, opts ...grpc.CallOption) (*AccountInformation, error)
}

type accountInformationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountInformationServiceClient(cc grpc.ClientConnInterface) AccountInformationServiceClient {
	return &accountInformationServiceClient{cc}
}

func (c *accountInformationServiceClient) Get(ctx context.Context, in *ClientId, opts ...grpc.CallOption) (*AccountInformation, error) {
	out := new(AccountInformation)
	err := c.cc.Invoke(ctx, AccountInformationService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountInformationServiceServer is the server API for AccountInformationService service.
// All implementations must embed UnimplementedAccountInformationServiceServer
// for forward compatibility
type AccountInformationServiceServer interface {
	Get(context.Context, *ClientId) (*AccountInformation, error)
	mustEmbedUnimplementedAccountInformationServiceServer()
}

// UnimplementedAccountInformationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountInformationServiceServer struct {
}

func (UnimplementedAccountInformationServiceServer) Get(context.Context, *ClientId) (*AccountInformation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAccountInformationServiceServer) mustEmbedUnimplementedAccountInformationServiceServer() {
}

// UnsafeAccountInformationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountInformationServiceServer will
// result in compilation errors.
type UnsafeAccountInformationServiceServer interface {
	mustEmbedUnimplementedAccountInformationServiceServer()
}

func RegisterAccountInformationServiceServer(s grpc.ServiceRegistrar, srv AccountInformationServiceServer) {
	s.RegisterService(&AccountInformationService_ServiceDesc, srv)
}

func _AccountInformationService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountInformationService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServiceServer).Get(ctx, req.(*ClientId))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountInformationService_ServiceDesc is the grpc.ServiceDesc for AccountInformationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountInformationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accountinformation.AccountInformationService",
	HandlerType: (*AccountInformationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _AccountInformationService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_information.proto",
}
