version: "3.6"

services:
  finance:
    image: sirius-finance-hub:latest
    build:
      context: ..
      dockerfile: ./docker/sirius-finance-hub/Dockerfile
    ports: ["8888:8888"]
    environment:
      PORT: 8888
      SIRIUS_URL: http://json-server:3000
      PREFIX: /supervision/finance
      FEATURES:

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'

  cypress:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./docker/cypress/Dockerfile
    command: ["--headless", "-b", "chrome"]
    volumes:
      - ../cypress/screenshots:/root/cypress/screenshots:rw,delegated
      - ../cypress/logs:/root/cypress/logs:rw,delegated
    depends_on:
      - finance
      - json-server
