FROM outofcoffee/imposter:4.8.0

COPY api-mocks/allpay/allpay-config.yml /opt/imposter/config/allpay-config.yml
COPY api-mocks/allpay/openapi.yml /opt/imposter/config/openapi.yml
COPY api-mocks/allpay/data/ /opt/imposter/config/data/
COPY api-mocks/allpay/scripts /opt/imposter/config/scripts
