FROM outofcoffee/imposter-distroless:4.7.0

COPY api-mocks/allpay/allpay-config.yml /opt/imposter/config/allpay-config.yml
COPY api-mocks/allpay/openapi.yml /opt/imposter/config/openapi.yml
COPY api-mocks/allpay/data/ /opt/imposter/config/data/
