FROM outofcoffee/imposter:4.9.3@sha256:ff25c8708944ec81a1992cd33433bbd032f12d64ded32ec1e6825810a5f2d5cb

COPY api-mocks/allpay/allpay-config.yml /opt/imposter/config/allpay-config.yml
COPY api-mocks/allpay/openapi.yml /opt/imposter/config/openapi.yml
COPY api-mocks/allpay/data/ /opt/imposter/config/data/
COPY api-mocks/allpay/scripts /opt/imposter/config/scripts
