// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: adhoc.sql

package store

import (
	"context"
)

const updateRefundLedgerAmounts = `-- name: UpdateRefundLedgerAmounts :execrows
UPDATE ledger
SET amount = -amount
WHERE type = 'REFUND'
  AND amount > 0
`

func (q *Queries) UpdateRefundLedgerAmounts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, updateRefundLedgerAmounts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
