// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: adhoc.sql

package store

import (
	"context"
)

const changePendingCollectionDate = `-- name: ChangePendingCollectionDate :execrows
UPDATE pending_collection
SET collection_date = '2026-05-26'
WHERE collection_date = '2026-05-25'
`

func (q *Queries) ChangePendingCollectionDate(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, changePendingCollectionDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
