// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: annual_billing_information.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnnualBillingLettersInformation = `-- name: GetAnnualBillingLettersInformation :many
SELECT
    COUNT(DISTINCT i.id) AS count,
    COALESCE(ies.status, 'UNPROCESSED') AS status,
    fc.payment_method AS payment_method
FROM supervision_finance.invoice i
    JOIN public.persons c ON i.person_id = c.id
    JOIN supervision_finance.finance_client fc ON fc.client_id = c.id
    JOIN public.cases o ON o.client_id = i.person_id
    LEFT JOIN supervision_finance.invoice_email_status ies ON i.id = ies.invoice_id
WHERE i.startdate::DATE >= $1::DATE
  AND i.enddate::DATE <= $2::DATE
  AND i.feetype NOT IN ('N2', 'N3')
  AND (
    (
      ies.invoice_id IS NULL
      AND o.orderstatus = 'ACTIVE'
      AND c.clientstatus <> 'DEATH_NOTIFIED'
    )
    OR ies.invoice_id IS NOT NULL
)
GROUP BY ies.status, fc.payment_method
`

type GetAnnualBillingLettersInformationParams struct {
	Column1 pgtype.Date
	Column2 pgtype.Date
}

type GetAnnualBillingLettersInformationRow struct {
	Count         pgtype.Int8
	Status        pgtype.Text
	PaymentMethod string
}

// non direct debit counts - is this still accurate?
func (q *Queries) GetAnnualBillingLettersInformation(ctx context.Context, arg GetAnnualBillingLettersInformationParams) ([]GetAnnualBillingLettersInformationRow, error) {
	rows, err := q.db.Query(ctx, getAnnualBillingLettersInformation, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnnualBillingLettersInformationRow
	for rows.Next() {
		var i GetAnnualBillingLettersInformationRow
		if err := rows.Scan(&i.Count, &i.Status, &i.PaymentMethod); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnnualBillingYear = `-- name: GetAnnualBillingYear :one
SELECT value FROM supervision_finance.property WHERE key = 'AnnualBillingYear' LIMIT 1
`

func (q *Queries) GetAnnualBillingYear(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getAnnualBillingYear)
	var value string
	err := row.Scan(&value)
	return value, err
}
