// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: direct_debits.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingCollection = `-- name: CancelPendingCollection :exec
UPDATE pending_collection
SET status = 'CANCELLED'
WHERE id = $1
`

func (q *Queries) CancelPendingCollection(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelPendingCollection, id)
	return err
}

const checkPendingCollection = `-- name: CheckPendingCollection :one
SELECT EXISTS (SELECT 1
               FROM pending_collection pc
                        JOIN supervision_finance.finance_client fc ON fc.id = pc.finance_client_id
               WHERE pc.collection_date = $1::DATE
                 AND pc.amount = $2
                 AND fc.client_id = $3
                 AND pc.status = 'PENDING')
`

type CheckPendingCollectionParams struct {
	DateCollected pgtype.Date
	Amount        pgtype.Int4
	ClientID      pgtype.Int4
}

func (q *Queries) CheckPendingCollection(ctx context.Context, arg CheckPendingCollectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPendingCollection, arg.DateCollected, arg.Amount, arg.ClientID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPendingCollection = `-- name: CreatePendingCollection :exec
INSERT INTO pending_collection (id, finance_client_id, collection_date, amount, status, created_at, created_by)
VALUES (NEXTVAL('pending_collection_id_seq'),
        (SELECT id FROM finance_client WHERE client_id = $1),
        $2,
        $3,
        'PENDING',
        NOW(),
        $4)
`

type CreatePendingCollectionParams struct {
	ClientID       int32
	CollectionDate pgtype.Date
	Amount         int32
	CreatedBy      int32
}

func (q *Queries) CreatePendingCollection(ctx context.Context, arg CreatePendingCollectionParams) error {
	_, err := q.db.Exec(ctx, createPendingCollection,
		arg.ClientID,
		arg.CollectionDate,
		arg.Amount,
		arg.CreatedBy,
	)
	return err
}

const getPendingCollections = `-- name: GetPendingCollections :many
SELECT pc.id, pc.amount, pc.collection_date
FROM pending_collection pc
         JOIN finance_client fc ON pc.finance_client_id = fc.id
WHERE pc.status = 'PENDING'
  AND fc.client_id = $1
ORDER BY pc.collection_date
`

type GetPendingCollectionsRow struct {
	ID             int32
	Amount         int32
	CollectionDate pgtype.Date
}

func (q *Queries) GetPendingCollections(ctx context.Context, clientID int32) ([]GetPendingCollectionsRow, error) {
	rows, err := q.db.Query(ctx, getPendingCollections, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingCollectionsRow
	for rows.Next() {
		var i GetPendingCollectionsRow
		if err := rows.Scan(&i.ID, &i.Amount, &i.CollectionDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingCollectionsForDate = `-- name: GetPendingCollectionsForDate :many
SELECT pc.id, pc.amount, fc.court_ref
FROM pending_collection pc
         JOIN supervision_finance.finance_client fc ON fc.id = pc.finance_client_id
WHERE pc.collection_date = $1::DATE
  AND pc.status = 'PENDING'
`

type GetPendingCollectionsForDateRow struct {
	ID       int32
	Amount   int32
	CourtRef pgtype.Text
}

func (q *Queries) GetPendingCollectionsForDate(ctx context.Context, dateCollected pgtype.Date) ([]GetPendingCollectionsForDateRow, error) {
	rows, err := q.db.Query(ctx, getPendingCollectionsForDate, dateCollected)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingCollectionsForDateRow
	for rows.Next() {
		var i GetPendingCollectionsForDateRow
		if err := rows.Scan(&i.ID, &i.Amount, &i.CourtRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOutstandingBalance = `-- name: GetPendingOutstandingBalance :one
WITH finance_client_id AS (SELECT id
                           FROM finance_client
                           WHERE client_id = $1
                           LIMIT 1),
     debt AS (SELECT fc.id, SUM(i.amount) AS debt
              FROM finance_client_id fc
                       LEFT JOIN invoice i ON fc.id = i.finance_client_id
              GROUP BY fc.id),
     pending AS (SELECT fc.id, SUM(pc.amount) AS pending
                 FROM pending_collection pc
                          JOIN finance_client_id fc ON pc.finance_client_id = fc.id
                 WHERE status = 'PENDING'
                 GROUP BY fc.id),
     credit AS (SELECT fc.id, SUM(la.amount) AS credit
                FROM ledger l
                         JOIN ledger_allocation la ON l.id = la.ledger_id
                         JOIN finance_client_id fc ON l.finance_client_id = fc.id
                WHERE l.status = 'CONFIRMED'
                  AND (
                    la.status = 'ALLOCATED' OR
                    (la.status IN ('UNAPPLIED', 'REAPPLIED') AND la.invoice_id IS NOT NULL)
                    )
                GROUP BY fc.id)
SELECT (COALESCE(d.debt, 0) - COALESCE(c.credit, 0) - COALESCE(p.pending, 0))::INT
FROM debt d
         LEFT JOIN credit c ON c.id = d.id
         LEFT JOIN pending p ON p.id = d.id
`

func (q *Queries) GetPendingOutstandingBalance(ctx context.Context, clientID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getPendingOutstandingBalance, clientID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const markPendingCollectionAsCollected = `-- name: MarkPendingCollectionAsCollected :exec
UPDATE pending_collection
SET ledger_id = $1,
    status    = 'COLLECTED'
WHERE id = $2
`

type MarkPendingCollectionAsCollectedParams struct {
	LedgerID pgtype.Int4
	ID       int32
}

func (q *Queries) MarkPendingCollectionAsCollected(ctx context.Context, arg MarkPendingCollectionAsCollectedParams) error {
	_, err := q.db.Exec(ctx, markPendingCollectionAsCollected, arg.LedgerID, arg.ID)
	return err
}
