// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: fee_reductions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFeeReductions = `-- name: GetFeeReductions :many
select fr.id,
       type,
       startdate,
       enddate,
       datereceived,
       notes,
       deleted
from fee_reduction fr
         inner join finance_client fc on fc.id = fr.finance_client_id
where fr.finance_client_id = $1
order by enddate desc, deleted
`

type GetFeeReductionsRow struct {
	ID           int32
	Type         string
	Startdate    pgtype.Date
	Enddate      pgtype.Date
	Datereceived pgtype.Date
	Notes        string
	Deleted      bool
}

func (q *Queries) GetFeeReductions(ctx context.Context, financeClientID pgtype.Int4) ([]GetFeeReductionsRow, error) {
	rows, err := q.db.Query(ctx, getFeeReductions, financeClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeeReductionsRow
	for rows.Next() {
		var i GetFeeReductionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Startdate,
			&i.Enddate,
			&i.Datereceived,
			&i.Notes,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
