// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: invoice_fee_rangers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInvoiceFeeRangersAmount = `-- name: GetInvoiceFeeRangersAmount :one
select sum(amount) / 2
from invoice_fee_range
where invoice_id = $1 and supervisionlevel = $2
`

type GetInvoiceFeeRangersAmountParams struct {
	InvoiceID        pgtype.Int4
	Supervisionlevel string
}

func (q *Queries) GetInvoiceFeeRangersAmount(ctx context.Context, arg GetInvoiceFeeRangersAmountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getInvoiceFeeRangersAmount, arg.InvoiceID, arg.Supervisionlevel)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
