// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: invoice_fee_range.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInvoiceFeeRangerAmount = `-- name: GetInvoiceFeeRangerAmount :one
select sum(amount) / 2
from invoice_fee_range
where invoice_id = $1 and supervisionlevel = $2
`

type GetInvoiceFeeRangerAmountParams struct {
	InvoiceID        pgtype.Int4
	Supervisionlevel string
}

func (q *Queries) GetInvoiceFeeRangerAmount(ctx context.Context, arg GetInvoiceFeeRangerAmountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getInvoiceFeeRangerAmount, arg.InvoiceID, arg.Supervisionlevel)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
