// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: invoice_fee_range.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInvoiceFeeRangeAmount = `-- name: GetInvoiceFeeRangeAmount :one
SELECT SUM(amount) / 2
FROM supervision_finance.invoice_fee_range
WHERE invoice_id = $1
  AND supervisionlevel = $2
`

type GetInvoiceFeeRangeAmountParams struct {
	InvoiceID        pgtype.Int4
	Supervisionlevel string
}

func (q *Queries) GetInvoiceFeeRangeAmount(ctx context.Context, arg GetInvoiceFeeRangeAmountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getInvoiceFeeRangeAmount, arg.InvoiceID, arg.Supervisionlevel)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
