// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_method.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPaymentMethod = `-- name: AddPaymentMethod :one
INSERT INTO payment_method (id, finance_client_id, type, created_by, created_at)
VALUES (NEXTVAL('payment_method_id_seq'),
        (SELECT id FROM finance_client WHERE client_id = $1),
        $2,
        $3,
        now())
RETURNING id, finance_client_id, type, created_at, created_by
`

type AddPaymentMethodParams struct {
	ClientID  int32
	Type      string
	CreatedBy int32
}

func (q *Queries) AddPaymentMethod(ctx context.Context, arg AddPaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, addPaymentMethod, arg.ClientID, arg.Type, arg.CreatedBy)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.FinanceClientID,
		&i.Type,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPaymentMethods = `-- name: GetPaymentMethods :many
SELECT pm.id,
       finance_client_id,
       type,
       created_by,
       created_at
FROM payment_method pm
WHERE pm.finance_client_id = $1
ORDER BY created_at DESC
`

type GetPaymentMethodsRow struct {
	ID              int32
	FinanceClientID int32
	Type            string
	CreatedBy       int32
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) GetPaymentMethods(ctx context.Context, financeClientID int32) ([]GetPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, getPaymentMethods, financeClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentMethodsRow
	for rows.Next() {
		var i GetPaymentMethodsRow
		if err := rows.Scan(
			&i.ID,
			&i.FinanceClientID,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
