// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_method.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setPaymentMethod = `-- name: SetPaymentMethod :exec
WITH this_payment_method AS (
    INSERT INTO payment_method (id, finance_client_id, type, created_by, created_at)
VALUES (NEXTVAL('payment_method_id_seq'),
        (SELECT id FROM finance_client WHERE client_id = $2),
        $1,
        $3,
        now()))
UPDATE finance_client
 SET payment_method = $1
 WHERE client_id = $2
`

type SetPaymentMethodParams struct {
	PaymentMethod pgtype.Text
	ClientID      pgtype.Int4
	CreatedBy     pgtype.Int4
}

func (q *Queries) SetPaymentMethod(ctx context.Context, arg SetPaymentMethodParams) error {
	_, err := q.db.Exec(ctx, setPaymentMethod, arg.PaymentMethod, arg.ClientID, arg.CreatedBy)
	return err
}
