// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending_collections.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingCollection = `-- name: CreatePendingCollection :exec
INSERT INTO pending_collection (id, finance_client_id, collection_date, amount, created_at, created_by)
VALUES (NEXTVAL('pending_collection_id_seq'),
        (SELECT id FROM finance_client WHERE client_id = $1),
        $2,
        $3,
        NOW(),
        $4)
`

type CreatePendingCollectionParams struct {
	ClientID       int32
	CollectionDate pgtype.Date
	Amount         int32
	CreatedBy      int32
}

func (q *Queries) CreatePendingCollection(ctx context.Context, arg CreatePendingCollectionParams) error {
	_, err := q.db.Exec(ctx, createPendingCollection,
		arg.ClientID,
		arg.CollectionDate,
		arg.Amount,
		arg.CreatedBy,
	)
	return err
}
