// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending_collections.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingCollection = `-- name: CreatePendingCollection :exec
INSERT INTO pending_collection (id, finance_client_id, collection_date, amount, created_at, created_by)
VALUES (NEXTVAL('pending_collection_id_seq'),
        (SELECT id FROM finance_client WHERE client_id = $1),
        $2,
        $3,
        NOW(),
        $4)
`

type CreatePendingCollectionParams struct {
	ClientID       int32
	CollectionDate pgtype.Date
	Amount         int32
	CreatedBy      int32
}

func (q *Queries) CreatePendingCollection(ctx context.Context, arg CreatePendingCollectionParams) error {
	_, err := q.db.Exec(ctx, createPendingCollection,
		arg.ClientID,
		arg.CollectionDate,
		arg.Amount,
		arg.CreatedBy,
	)
	return err
}

const getPendingCollectionsForDate = `-- name: GetPendingCollectionsForDate :many
SELECT pc.id, pc.amount, fc.court_ref
FROM pending_collection pc
         JOIN supervision_finance.finance_client fc ON fc.id = pc.finance_client_id
WHERE pc.collection_date = $1::DATE
  AND pc.ledger_id IS NULL
`

type GetPendingCollectionsForDateRow struct {
	ID       int32
	Amount   int32
	CourtRef pgtype.Text
}

func (q *Queries) GetPendingCollectionsForDate(ctx context.Context, dateCollected pgtype.Date) ([]GetPendingCollectionsForDateRow, error) {
	rows, err := q.db.Query(ctx, getPendingCollectionsForDate, dateCollected)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingCollectionsForDateRow
	for rows.Next() {
		var i GetPendingCollectionsForDateRow
		if err := rows.Scan(&i.ID, &i.Amount, &i.CourtRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPendingCollectionAsCollected = `-- name: MarkPendingCollectionAsCollected :exec
UPDATE pending_collection
SET ledger_id = $1
WHERE id = $2
`

type MarkPendingCollectionAsCollectedParams struct {
	LedgerID pgtype.Int4
	ID       int32
}

func (q *Queries) MarkPendingCollectionAsCollected(ctx context.Context, arg MarkPendingCollectionAsCollectedParams) error {
	_, err := q.db.Exec(ctx, markPendingCollectionAsCollected, arg.LedgerID, arg.ID)
	return err
}
