// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refunds.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRefund = `-- name: CancelRefund :exec
UPDATE refund
SET cancelled_at = NOW(),
    cancelled_by = $1
WHERE id = $2
  AND finance_client_id = (SELECT id FROM finance_client WHERE client_id = $3)
  AND fulfilled_at IS NULL
`

type CancelRefundParams struct {
	CancelledBy pgtype.Int4
	RefundID    pgtype.Int4
	ClientID    pgtype.Int4
}

func (q *Queries) CancelRefund(ctx context.Context, arg CancelRefundParams) error {
	_, err := q.db.Exec(ctx, cancelRefund, arg.CancelledBy, arg.RefundID, arg.ClientID)
	return err
}

const checkRefundForReversalExists = `-- name: CheckRefundForReversalExists :one
SELECT EXISTS (SELECT 1
               FROM refund r
                        JOIN supervision_finance.finance_client fc ON fc.id = r.finance_client_id
               WHERE fc.court_ref = $1
                 AND r.fulfilled_at::DATE = $2::DATE
                 AND r.amount = $3)
`

type CheckRefundForReversalExistsParams struct {
	CourtRef      pgtype.Text
	FulfilledDate pgtype.Date
	Amount        pgtype.Int4
}

func (q *Queries) CheckRefundForReversalExists(ctx context.Context, arg CheckRefundForReversalExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkRefundForReversalExists, arg.CourtRef, arg.FulfilledDate, arg.Amount)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createRefund = `-- name: CreateRefund :one
WITH r AS (
    INSERT INTO refund (id, finance_client_id, raised_date, amount, decision, notes, created_by, created_at)
        VALUES (NEXTVAL('refund_id_seq'),
                (SELECT id FROM finance_client WHERE client_id = $1),
                NOW(),
                $2,
                'PENDING',
                $3,
                $4,
                NOW())
        RETURNING id),
     b AS (
         INSERT INTO bank_details (id, refund_id, name, account, sort_code)
             SELECT NEXTVAL('refund_id_seq'), r.id, $5, $6, $7
             FROM r)
SELECT id
FROM r
`

type CreateRefundParams struct {
	ClientID      int32
	Amount        int32
	Notes         string
	CreatedBy     int32
	AccountName   string
	AccountNumber string
	SortCode      string
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.ClientID,
		arg.Amount,
		arg.Notes,
		arg.CreatedBy,
		arg.AccountName,
		arg.AccountNumber,
		arg.SortCode,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const expireApprovedRefunds = `-- name: ExpireApprovedRefunds :many
WITH expired_refunds AS (
    UPDATE refund
        SET cancelled_at = NOW(), cancelled_by = $1
        WHERE processed_at IS NULL AND decision_at::DATE < CURRENT_DATE - INTERVAL '14 days'
        RETURNING id),
     deleted_bank_details AS (DELETE
         FROM bank_details
             WHERE refund_id IN (SELECT id FROM expired_refunds))
SELECT COUNT(*)
FROM expired_refunds
`

func (q *Queries) ExpireApprovedRefunds(ctx context.Context, cancelledBy pgtype.Int4) ([]int64, error) {
	rows, err := q.db.Query(ctx, expireApprovedRefunds, cancelledBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var count int64
		if err := rows.Scan(&count); err != nil {
			return nil, err
		}
		items = append(items, count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expirePendingRefunds = `-- name: ExpirePendingRefunds :many
WITH expired_refunds AS (
    UPDATE refund
        SET decision = 'REJECTED', decision_at = NOW(), decision_by = $1
        WHERE decision = 'PENDING' AND created_at::DATE < CURRENT_DATE - INTERVAL '14 days'
        RETURNING id),
     deleted_bank_details AS (DELETE
         FROM bank_details
             WHERE refund_id IN (SELECT id FROM expired_refunds))
SELECT COUNT(*)
FROM expired_refunds
`

func (q *Queries) ExpirePendingRefunds(ctx context.Context, decisionBy pgtype.Int4) ([]int64, error) {
	rows, err := q.db.Query(ctx, expirePendingRefunds, decisionBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var count int64
		if err := rows.Scan(&count); err != nil {
			return nil, err
		}
		items = append(items, count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireProcessingRefunds = `-- name: ExpireProcessingRefunds :many
WITH expired_refunds AS (
    UPDATE refund
        SET cancelled_at = NOW(), cancelled_by = $1
        WHERE cancelled_at IS NULL AND fulfilled_at IS NULL AND processed_at::DATE < CURRENT_DATE - INTERVAL '14 days'
        RETURNING id),
     deleted_bank_details AS (DELETE
         FROM bank_details
             WHERE refund_id IN (SELECT id FROM expired_refunds))
SELECT COUNT(*)
FROM expired_refunds
`

func (q *Queries) ExpireProcessingRefunds(ctx context.Context, cancelledBy pgtype.Int4) ([]int64, error) {
	rows, err := q.db.Query(ctx, expireProcessingRefunds, cancelledBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var count int64
		if err := rows.Scan(&count); err != nil {
			return nil, err
		}
		items = append(items, count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessingRefund = `-- name: GetProcessingRefund :one
SELECT r.id
FROM refund r
         JOIN supervision_finance.bank_details bd ON r.id = bd.refund_id
         JOIN supervision_finance.finance_client fc ON fc.id = r.finance_client_id
WHERE fc.court_ref = $1
  AND r.decision = 'APPROVED'
  AND r.processed_at IS NOT NULL
  AND r.fulfilled_at IS NULL
  AND r.amount = $2
  AND bd.name = $3
  AND bd.account = $4
  AND REPLACE(bd.sort_code, '-', '') = $5
`

type GetProcessingRefundParams struct {
	CourtRef      pgtype.Text
	Amount        pgtype.Int4
	AccountName   pgtype.Text
	AccountNumber pgtype.Text
	SortCode      pgtype.Text
}

func (q *Queries) GetProcessingRefund(ctx context.Context, arg GetProcessingRefundParams) (int32, error) {
	row := q.db.QueryRow(ctx, getProcessingRefund,
		arg.CourtRef,
		arg.Amount,
		arg.AccountName,
		arg.AccountNumber,
		arg.SortCode,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRefundAmount = `-- name: GetRefundAmount :one
SELECT ABS(COALESCE(SUM(
                            CASE
                                WHEN la.status IN ('UNAPPLIED', 'REAPPLIED')
                                    THEN la.amount
                                ELSE 0
                                END), 0))::INT AS credit
FROM finance_client fc
         LEFT JOIN ledger l ON fc.id = l.finance_client_id AND l.status = 'CONFIRMED'
         LEFT JOIN ledger_allocation la ON l.id = la.ledger_id
WHERE fc.client_id = $1
`

func (q *Queries) GetRefundAmount(ctx context.Context, clientID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getRefundAmount, clientID)
	var credit int32
	err := row.Scan(&credit)
	return credit, err
}

const getRefunds = `-- name: GetRefunds :many
SELECT r.id,
       r.raised_date,
       r.fulfilled_at::DATE                AS fulfilled_date,
       r.amount,
       CASE
           WHEN r.fulfilled_at IS NOT NULL THEN 'FULFILLED'
           WHEN r.cancelled_at IS NOT NULL THEN 'CANCELLED'
           WHEN r.processed_at IS NOT NULL THEN 'PROCESSING'
           ELSE r.decision
           END::VARCHAR                    AS status,
       r.notes,
       r.created_by,
       COALESCE(bd.name, '')::VARCHAR      AS account_name,
       COALESCE(bd.account, '')::VARCHAR   AS account_code,
       COALESCE(bd.sort_code, '')::VARCHAR AS sort_code
FROM refund r
         JOIN finance_client fc ON fc.id = r.finance_client_id
         LEFT JOIN bank_details bd ON r.id = bd.refund_id
WHERE fc.client_id = $1
ORDER BY r.raised_date DESC, r.created_at DESC
`

type GetRefundsRow struct {
	ID            int32
	RaisedDate    pgtype.Date
	FulfilledDate pgtype.Date
	Amount        int32
	Status        string
	Notes         string
	CreatedBy     int32
	AccountName   string
	AccountCode   string
	SortCode      string
}

func (q *Queries) GetRefunds(ctx context.Context, clientID int32) ([]GetRefundsRow, error) {
	rows, err := q.db.Query(ctx, getRefunds, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefundsRow
	for rows.Next() {
		var i GetRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.RaisedDate,
			&i.FulfilledDate,
			&i.Amount,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.AccountName,
			&i.AccountCode,
			&i.SortCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefundsAsFulfilled = `-- name: MarkRefundsAsFulfilled :exec
UPDATE refund
SET fulfilled_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRefundsAsFulfilled(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markRefundsAsFulfilled, id)
	return err
}

const markRefundsAsProcessed = `-- name: MarkRefundsAsProcessed :many
UPDATE refund
SET processed_at = NOW()
WHERE decision = 'APPROVED'
  AND processed_at IS NULL
RETURNING id
`

func (q *Queries) MarkRefundsAsProcessed(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, markRefundsAsProcessed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBankDetails = `-- name: RemoveBankDetails :exec
DELETE
FROM bank_details
WHERE refund_id = $1
`

func (q *Queries) RemoveBankDetails(ctx context.Context, refundID int32) error {
	_, err := q.db.Exec(ctx, removeBankDetails, refundID)
	return err
}

const setRefundDecision = `-- name: SetRefundDecision :exec
UPDATE refund
SET decision    = $1,
    decision_at = NOW(),
    decision_by = $2
WHERE finance_client_id = (SELECT id FROM finance_client WHERE client_id = $3)
  AND id = $4
`

type SetRefundDecisionParams struct {
	Decision   pgtype.Text
	DecisionBy pgtype.Int4
	ClientID   pgtype.Int4
	RefundID   pgtype.Int4
}

func (q *Queries) SetRefundDecision(ctx context.Context, arg SetRefundDecisionParams) error {
	_, err := q.db.Exec(ctx, setRefundDecision,
		arg.Decision,
		arg.DecisionBy,
		arg.ClientID,
		arg.RefundID,
	)
	return err
}
