// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: users.sql

package store

import (
	"context"
)

const currentUser = `-- name: CurrentUser :one
SELECT id, name, email, roles FROM users LIMIT 1
`

func (q *Queries) CurrentUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, currentUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Roles,
	)
	return i, err
}
