---
env:
  contexts:
  - name: "FinanceHub"
    urls:
    - "http://finance-hub:8888/finance/clients/99/invoices"
    includePaths:
    - "http://finance-hub:8888/finance/.*"
  parameters:
    failOnError: false
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    context: "FinanceHub"
    url: "http://finance-hub:8888/finance/clients/99/invoices"
    maxDepth: 10
    maxParseSizeBytes: 26214400
  name: "spider"
  type: "spider"
- parameters:
    maxDuration: 10
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    context: "FinanceHub"
    url: "http://finance-hub:8888/finance/clients/99/invoices"
    maxDuration: 0
    maxCrawlDepth: 20
    numberOfBrowsers: 2
    eventWait: 5000
    reloadWait: 5000
  name: "spiderAjax"
  type: "spiderAjax"
- parameters:
    maxDuration: 10
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    context: "FinanceHub"
    threadPerHost: 5
  policyDefinition:
    defaultStrength: "Insane"
    defaultThreshold: "Low"
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    maxDuration: 10
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    template: "traditional-html-plus"
    theme: "light"
    reportDir: "/zap/wrk/FinanceHubReport"
    reportFile: "ZapReportExtended.html"
    reportTitle: "Finance Hub ZAP Extended Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "low"
  - "medium"
  - "high"
  confidences:
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "passingrules"
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  - "params"
  - "chart"
  - "statistics"
  - "sequencedetails"
  name: "Finance Hub ZAP Extended Report"
  type: "report"
- parameters:
    template: "traditional-pdf"
    reportDir: "/zap/wrk/"
    reportFile: "FinanceHubReport.pdf"
    reportTitle: "PDF Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "info"
  - "low"
  - "medium"
  - "high"
  confidences:
  - "falsepositive"
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  name: "PDF Report"
  type: "report"
